CHILDREN: str = 'children'
BROWSE_NAME: str = 'browse_name' 
DISPLAY_NAME: str = 'display_name'
NODE_ID: str = 'node_id'
NODE_CLASS: str = 'node_class'
ROOT: str = 'root'
VALUE: str = 'value'
DATA_TYPE: str = 'default_value'
    
END_POINT: str = 'opc_endpoint_to_scan' 
STRUCT_FILE: str = 'save_scan_file'
OPC_SETTINGS: str = 'opc_settings'
UDT_ENTRY_INDEX: str = 'udt_entry_index'
